#!/bin/sh
# Start with tinyconfig, then add only the facilities Felix's ISO uses.
set -eu
root=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)
src=${FELIX_KERNEL_DIR:-/var/tmp/felix-linux/kernel}
cd "$src"
make ARCH=x86 tinyconfig
c=scripts/config
for option in 64BIT SMP MODULES DRM SOUND BT IPV6 DEBUG_KERNEL; do
    "$c" --disable "$option"
done
for option in X86_32 M686 EXPERT PRINTK BUG MULTIUSER FUTEX EPOLL SIGNALFD TIMERFD EVENTFD SHMEM AIO ADVISE_SYSCALLS FHANDLE POSIX_TIMERS SYSVIPC SYSCTL ELF_CORE BINFMT_ELF BINFMT_SCRIPT COREDUMP TTY VT VT_CONSOLE UNIX98_PTYS LEGACY_PTYS UNIX INET NET NETDEVICES ETHERNET NET_VENDOR_INTEL E1000 PCI PCI_DIRECT BLOCK BLK_DEV_INITRD RD_GZIP RD_XZ DEVTMPFS DEVTMPFS_MOUNT PROC_FS SYSFS TMPFS TMPFS_POSIX_ACL FILE_LOCKING INOTIFY_USER DNOTIFY INPUT INPUT_KEYBOARD KEYBOARD_ATKBD INPUT_MOUSE MOUSE_PS2 INPUT_MOUSEDEV INPUT_EVDEV SERIO SERIO_I8042 SERIO_LIBPS2 HID GENERIC_IRQ_DEBUGFS SERIAL_8250 SERIAL_8250_CONSOLE RTC_CLASS RTC_DRV_CMOS RTC_HCTOSYS ACPI ACPI_SYSTEM_POWER_STATES X86_PM_TIMER REBOOT_MODE FB FB_VESA FB_CORE FB_DEVICE FB_MODE_HELPERS FRAMEBUFFER_CONSOLE VGA_CONSOLE FONT_8x16 FONT_8x8 DUMMY_CONSOLE CRC32 EXT4_FS FAT_FS VFAT_FS NLS NLS_CODEPAGE_437 NLS_ISO8859_1 ATA ATA_PIIX SCSI BLK_DEV_SD; do
    "$c" --enable "$option"
done
"$c" --enable PACKET --enable COMPAT_32BIT_TIME
for option in ISO9660_FS JOLIET CDROM BLK_DEV_SR SATA_AHCI NVME_CORE BLK_DEV_NVME VIRTIO_PCI VIRTIO_BLK USB_STORAGE MSDOS_PARTITION; do "$c" --enable "$option"; done
# Wi-Fi: nl80211/mac80211, radio switches, firmware loading, and common
# Atheros/Ralink/Realtek USB and Atheros PCI adapters. Keep DRM disabled.
"$c" --enable NEW_LEDS --enable LEDS_CLASS
"$c" --enable FW_LOADER_COMPRESS --enable FW_LOADER_COMPRESS_ZSTD
for option in WIRELESS WLAN CFG80211 MAC80211 RFKILL FW_LOADER USB_SUPPORT USB USB_PCI USB_XHCI_HCD USB_XHCI_PCI USB_EHCI_HCD USB_EHCI_PCI USB_OHCI_HCD USB_OHCI_HCD_PCI USB_UHCI_HCD WLAN_VENDOR_ATH ATH_COMMON ATH9K ATH9K_PCI ATH9K_HTC WLAN_VENDOR_RALINK RT2X00 RT2800USB RT2800USB_RT33XX RT2800USB_RT35XX RT2800USB_RT53XX RT2800USB_RT55XX WLAN_VENDOR_REALTEK RTL8XXXU WLAN_VENDOR_MEDIATEK MT7601U CRYPTO CRYPTO_AES CRYPTO_CCM CRYPTO_GCM CRYPTO_SHA256 CRYPTO_HMAC; do
    "$c" --enable "$option"
done
"$c" --set-val DEFAULT_MMAP_MIN_ADDR 4096 --set-str DEFAULT_HOSTNAME felix --set-str LOCALVERSION -felix --disable LOCALVERSION_AUTO
# Ethernet: Intel, Realtek, Broadcom, virtual NICs and common USB adapters.
for option in NET_VENDOR_REALTEK NET_VENDOR_BROADCOM NET_VENDOR_AMD NET_VENDOR_VIA E1000E IGB R8169 8139CP 8139TOO TIGON3 PCNET32 VIA_RHINE VIRTIO_MENU VIRTIO_PCI VIRTIO_PCI_LEGACY VIRTIO_NET VMXNET3 MII PHYLIB USB_USBNET USB_NET_AX8817X USB_NET_AX88179_178A USB_RTL8152 USB_NET_CDCETHER USB_NET_CDC_NCM WLAN_VENDOR_INTEL IWLWIFI IWLDVM IWLMVM WLAN_VENDOR_BROADCOM BRCMUTIL BRCMSMAC BRCMFMAC BRCMFMAC_PCIE BRCMFMAC_USB B43 BCMA BCMA_HOST_PCI SSB SSB_PCIHOST; do
    "$c" --enable "$option"
done
make ARCH=x86 olddefconfig
# These are release invariants, rather than relying on fragment intent.
for option in X86_32 FB_VESA BINFMT_ELF DEVTMPFS DEVTMPFS_MOUNT INET E1000 E1000E IGB R8169 TIGON3 PCNET32 VIRTIO_NET VMXNET3 USB_RTL8152 USB_NET_AX88179_178A IWLWIFI IWLMVM BRCMFMAC BRCMSMAC CFG80211 MAC80211 RFKILL USB ATH9K ATH9K_HTC RT2800USB RTL8XXXU MT7601U FW_LOADER_COMPRESS_ZSTD ISO9660_FS BLK_DEV_SR SATA_AHCI BLK_DEV_NVME MSDOS_PARTITION; do
    grep -qx "CONFIG_${option}=y" .config || { echo "Missing required kernel option: $option" >&2; exit 1; }
done
for option in 64BIT DRM; do
    if grep -q "^CONFIG_${option}=[ym]" .config; then echo "Forbidden kernel option: $option" >&2; exit 1; fi
done
make ARCH=x86 -j"${JOBS:-8}" bzImage
mkdir -p "$root/build/release"
cp arch/x86/boot/bzImage "$root/build/release/vmlinuz"
cp .config "$root/build/release/kernel.config"
